"""7_migration_add_email_to_shared_link_access

Revision ID: 111f1318e436
Revises: a885b1015adc
Create Date: 2026-01-16 18:13:28.174158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "111f1318e436"
down_revision: Union[str, Sequence[str], None] = "a885b1015adc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shared_link_access", sa.Column("email", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_shared_link_access_email"),
        "shared_link_access",
        ["email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shared_link_access_email"), table_name="shared_link_access")
    op.drop_column("shared_link_access", "email")
    # ### end Alembic commands ###
