"""5_migration_assignment_google_forms

Revision ID: 2c041f13225f
Revises: 34a39d5b7fe8
Create Date: 2025-11-24 10:01:10.172187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c041f13225f"
down_revision: Union[str, Sequence[str], None] = "34a39d5b7fe8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments", sa.Column("google_form_url", sa.String(), nullable=True)
    )
    op.add_column(
        "assignments", sa.Column("google_form_response_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "google_form_response_url")
    op.drop_column("assignments", "google_form_url")
    # ### end Alembic commands ###
