"""6_migration_add_share_format_to_shared_links

Revision ID: 35b2a9a54370
Revises: 2c041f13225f
Create Date: 2026-01-06 19:45:31.041409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "35b2a9a54370"
down_revision: Union[str, Sequence[str], None] = "a885b1015adc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shared_links", sa.Column("share_format", sa.String(), nullable=True))
    # manually added default values for existing rows
    op.execute(
        "UPDATE shared_links SET share_format = 'html_form' WHERE share_format IS NULL"
    )
    op.alter_column(
        "shared_links", "share_format", nullable=False, server_default="html_form"
    )

    op.add_column(
        "shared_links", sa.Column("google_resource_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shared_links", "google_resource_url")
    op.drop_column("shared_links", "share_format")
    # ### end Alembic commands ###
