"""1.migration

Revision ID: 3892bf302c14
Revises:
Create Date: 2025-08-29 17:00:22.000652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3892bf302c14"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_folders_source_type"), "folders", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_folders_user_id"), "folders", ["user_id"], unique=False)
    op.create_table(
        "videos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("youtube_id", sa.String(), nullable=True),
        sa.Column("youtube_url", sa.String(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=True),
        sa.Column("thumb_key", sa.String(), nullable=True),
        sa.Column("transcript_s3_key", sa.String(), nullable=True),
        sa.Column("local_path", sa.String(), nullable=True),
        sa.Column("transcript_text", sa.Text(), nullable=True),
        sa.Column(
            "transcript_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("formatted_transcript", sa.Text(), nullable=True),
        sa.Column(
            "formatting_status", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "download_status", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("download_path", sa.String(), nullable=True),
        sa.Column(
            "upload_status", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "chat_sessions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("folder_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_folder_id"), "videos", ["folder_id"], unique=False)
    op.create_index(
        op.f("ix_videos_source_type"), "videos", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_videos_user_id"), "videos", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_videos_youtube_id"), "videos", ["youtube_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_videos_youtube_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_user_id"), table_name="videos")
    op.drop_index(op.f("ix_videos_source_type"), table_name="videos")
    op.drop_index(op.f("ix_videos_folder_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index(op.f("ix_folders_user_id"), table_name="folders")
    op.drop_index(op.f("ix_folders_source_type"), table_name="folders")
    op.drop_table("folders")
    # ### end Alembic commands ###
