"""11 migration Add submitted_by_user_id field for bulk uploads

Revision ID: 61ae8bccbbc8
Revises: 988d09ba0571
Create Date: 2026-02-12 16:45:01.089101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "61ae8bccbbc8"
down_revision: Union[str, Sequence[str], None] = "988d09ba0571"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions",
        sa.Column("submitted_by_user_id", sa.String(), nullable=True),
    )
    op.create_index(
        op.f("ix_assignment_submissions_submitted_by_user_id"),
        "assignment_submissions",
        ["submitted_by_user_id"],
        unique=False,
    )
    op.alter_column(
        "lecture_summaries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lecture_summaries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_index(
        op.f("ix_assignment_submissions_submitted_by_user_id"),
        table_name="assignment_submissions",
    )
    op.drop_column("assignment_submissions", "submitted_by_user_id")
    # ### end Alembic commands ###
