"""20_migration_add_material_chat_and_chunks

Revision ID: 67f1ee944a7a
Revises: c74b8c0ce64c
Create Date: 2026-05-25 08:51:51.480797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '67f1ee944a7a'
down_revision: Union[str, Sequence[str], None] = 'c74b8c0ce64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_material_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_material_id'], ['course_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_chat_sessions_course_material_id'), 'material_chat_sessions', ['course_material_id'], unique=False)
    op.create_index(op.f('ix_material_chat_sessions_user_id'), 'material_chat_sessions', ['user_id'], unique=False)
    op.create_table('material_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_material_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_material_id'], ['course_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_chunks_course_material_id'), 'material_chunks', ['course_material_id'], unique=False)
    op.create_table('material_chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['material_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_chat_messages_session_id'), 'material_chat_messages', ['session_id'], unique=False)
    op.add_column('course_materials', sa.Column('chunking_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'chunking_status')
    op.drop_index(op.f('ix_material_chat_messages_session_id'), table_name='material_chat_messages')
    op.drop_table('material_chat_messages')
    op.drop_index(op.f('ix_material_chunks_course_material_id'), table_name='material_chunks')
    op.drop_table('material_chunks')
    op.drop_index(op.f('ix_material_chat_sessions_user_id'), table_name='material_chat_sessions')
    op.drop_index(op.f('ix_material_chat_sessions_course_material_id'), table_name='material_chat_sessions')
    op.drop_table('material_chat_sessions')
    # ### end Alembic commands ###
