"""3_migration_assignment

Revision ID: 6fd55a6ea74e
Revises: 844eb09a670d
Create Date: 2025-09-15 22:10:16.859345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6fd55a6ea74e"
down_revision: Union[str, Sequence[str], None] = "844eb09a670d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assignments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("total_points", sa.String(), nullable=True),
        sa.Column("total_questions", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("engineering_level", sa.String(), nullable=True),
        sa.Column("engineering_discipline", sa.String(), nullable=True),
        sa.Column(
            "question_types", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "linked_videos", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "uploaded_files", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("generation_prompt", sa.Text(), nullable=True),
        sa.Column(
            "generation_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_template", sa.Boolean(), nullable=True),
        sa.Column("shared_count", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignments_user_id"), "assignments", ["user_id"], unique=False
    )
    op.create_table(
        "assignment_submissions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("assignment_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submission_method", sa.String(), nullable=True),
        sa.Column(
            "submitted_files", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("score", sa.String(), nullable=True),
        sa.Column("percentage", sa.String(), nullable=True),
        sa.Column("feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("overall_feedback", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("is_late", sa.Boolean(), nullable=True),
        sa.Column("attempt_number", sa.String(), nullable=True),
        sa.Column("time_spent", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("graded_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignment_submissions_user_id"),
        "assignment_submissions",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "shared_links", sa.Column("assignment_id", sa.String(), nullable=True)
    )
    op.create_foreign_key(
        None, "shared_links", "assignments", ["assignment_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shared_links", type_="foreignkey")
    op.drop_column("shared_links", "assignment_id")
    op.drop_index(
        op.f("ix_assignment_submissions_user_id"), table_name="assignment_submissions"
    )
    op.drop_table("assignment_submissions")
    op.drop_index(op.f("ix_assignments_user_id"), table_name="assignments")
    op.drop_table("assignments")
    # ### end Alembic commands ###
