"""2_migration_Add sharing tables

Revision ID: 844eb09a670d
Revises: 3892bf302c14
Create Date: 2025-09-02 16:54:24.785110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "844eb09a670d"
down_revision: Union[str, Sequence[str], None] = "3892bf302c14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shared_links",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("share_token", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("share_type", sa.String(), nullable=False),
        sa.Column("folder_id", sa.String(), nullable=True),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.Column("chat_session_id", sa.String(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("max_views", sa.String(), nullable=True),
        sa.Column("view_count", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shared_links_owner_id"), "shared_links", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_shared_links_share_token"),
        "shared_links",
        ["share_token"],
        unique=True,
    )
    op.create_table(
        "shared_link_access",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("shared_link_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("permission", sa.String(), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("accessed_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["shared_link_id"],
            ["shared_links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shared_link_access_user_id"),
        "shared_link_access",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shared_link_access_user_id"), table_name="shared_link_access"
    )
    op.drop_table("shared_link_access")
    op.drop_index(op.f("ix_shared_links_share_token"), table_name="shared_links")
    op.drop_index(op.f("ix_shared_links_owner_id"), table_name="shared_links")
    op.drop_table("shared_links")
    # ### end Alembic commands ###
