"""18 add_subject_fields_to_courses

Revision ID: 915759bda80e
Revises: 670cf945c6c8
Create Date: 2026-04-08 12:10:45.009682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "915759bda80e"
down_revision: Union[str, Sequence[str], None] = "670cf945c6c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("subject_category", sa.String(), nullable=True))
    op.add_column("courses", sa.Column("engineering_level", sa.String(), nullable=True))
    op.add_column(
        "courses", sa.Column("engineering_discipline", sa.String(), nullable=True)
    )
    op.drop_column("courses", "subject")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("courses", "engineering_discipline")
    op.drop_column("courses", "engineering_level")
    op.drop_column("courses", "subject_category")
    # ### end Alembic commands ###
