"""15 migration add_subject_category_to_assignments

Revision ID: a772ab660778
Revises: 7c4bff3c6756
Create Date: 2026-03-22 19:26:59.305987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a772ab660778"
down_revision: Union[str, Sequence[str], None] = "7c4bff3c6756"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignments", sa.Column("subject_category", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignments", "subject_category")
    # ### end Alembic commands ###
