"""6_migration_daily_usage_tracking

Revision ID: a885b1015adc
Revises: 2c041f13225f
Create Date: 2026-01-12 15:45:20.856066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a885b1015adc"
down_revision: Union[str, Sequence[str], None] = "2c041f13225f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_usage", sa.Column("date", sa.String(), nullable=False))
    op.add_column(
        "user_usage", sa.Column("videos_analyzed_today", sa.Integer(), nullable=False)
    )
    op.add_column(
        "user_usage", sa.Column("questions_per_video", sa.JSON(), nullable=False)
    )
    op.create_index(op.f("ix_user_usage_date"), "user_usage", ["date"], unique=False)
    # ### end Alembic commands ###
    # Update existing rows to have date based on month_year (set to first day of month)
    op.execute(
        """
        UPDATE user_usage
        SET date = month_year || '-01'
        WHERE date IS NULL
    """
    )
    # Now make date column NOT NULL
    op.alter_column("user_usage", "date", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_usage_date"), table_name="user_usage")
    op.drop_column("user_usage", "questions_per_video")
    op.drop_column("user_usage", "videos_analyzed_today")
    op.drop_column("user_usage", "date")
    # ### end Alembic commands ###
