"""21_migration_material_chunk_timestamps

Revision ID: b113c0df09ae
Revises: 67f1ee944a7a
Create Date: 2026-05-29 15:58:10.457890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b113c0df09ae"
down_revision: Union[str, Sequence[str], None] = "67f1ee944a7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course_materials",
        sa.Column(
            "transcript_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "material_chunks", sa.Column("start_seconds", sa.Float(), nullable=True)
    )
    op.add_column(
        "material_chunks", sa.Column("end_seconds", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("material_chunks", "end_seconds")
    op.drop_column("material_chunks", "start_seconds")
    op.drop_column("course_materials", "transcript_json")
    # ### end Alembic commands ###
