"""19 migration_assignment_reviews

Revision ID: c74b8c0ce64c
Revises: 915759bda80e
Create Date: 2026-05-23 16:59:11.363836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74b8c0ce64c'
down_revision: Union[str, Sequence[str], None] = '915759bda80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'user_id', name='uq_assignment_reviews_assignment_user')
    )
    op.create_index(op.f('ix_assignment_reviews_assignment_id'), 'assignment_reviews', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_reviews_user_id'), 'assignment_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_reviews_user_id'), table_name='assignment_reviews')
    op.drop_index(op.f('ix_assignment_reviews_assignment_id'), table_name='assignment_reviews')
    op.drop_table('assignment_reviews')
    # ### end Alembic commands ###
