"""8 migration Add AI detection fields

Revision ID: cdb37dd9d323
Revises: 111f1318e436
Create Date: 2026-01-30 12:32:27.370249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cdb37dd9d323"
down_revision: Union[str, Sequence[str], None] = "111f1318e436"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assignment_submissions",
        sa.Column(
            "telemetry_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assignment_submissions", "telemetry_data")
    # ### end Alembic commands ###
