"""add_google_forms_integration

Revision ID: ee779be77dc0
Revises: 34a39d5b7fe8
Create Date: 2025-11-17 09:49:35.530925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee779be77dc0'
down_revision: Union[str, Sequence[str], None] = '34a39d5b7fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('google_form_url', sa.String(), nullable=True))
    op.add_column('assignments', sa.Column('google_form_response_url', sa.String(), nullable=True))
    op.drop_index(op.f('idx_shared_links_export_format'), table_name='shared_links')
    op.drop_index(op.f('idx_shared_links_google_resource_id'), table_name='shared_links')
    op.drop_column('shared_links', 'last_response_sync')
    op.drop_column('shared_links', 'export_format')
    op.drop_column('shared_links', 'response_sync_status')
    op.drop_column('shared_links', 'google_resource_url')
    op.drop_column('shared_links', 'recipient_emails')
    op.drop_column('shared_links', 'google_resource_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_links', sa.Column('google_resource_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shared_links', sa.Column('recipient_emails', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shared_links', sa.Column('google_resource_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shared_links', sa.Column('response_sync_status', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('shared_links', sa.Column('export_format', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shared_links', sa.Column('last_response_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_shared_links_google_resource_id'), 'shared_links', ['google_resource_id'], unique=False)
    op.create_index(op.f('idx_shared_links_export_format'), 'shared_links', ['export_format'], unique=False)
    op.drop_column('assignments', 'google_form_response_url')
    op.drop_column('assignments', 'google_form_url')
    # ### end Alembic commands ###
